version: '3'

services:
  nextjs-app:
    container_name: NextApp
    build:
      context: ./
      dockerfile: Dockerfile
    # Set environment variables directly in the docker-compose file
    # Set envrionment variables based on the .env file
    # env_file:
    #   - .env
    volumes:
      - .:/app/
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    networks:
      - my_network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs-app
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
