services:
  nextjs-app:
    container_name: quetext-clone-prod
    build:
      context: ./
      dockerfile: prod.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    ports:
      - 3002:3002
    networks:
      - npm_network

networks:
  npm_network:
    external: true
