services:
  nextjs-app:
    container_name: quetext-clone
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - npm_network

networks:
  npm_network:
    external: true
